spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myeh-badminton
    username: root
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:sql/schema/schema.sql
      data-locations: ["classpath:sql/data/user-info.sql", "classpath:sql/data/brand.sql", "classpath:sql/data/item.sql"]